### ISSUE TITLE
Unknown / Visual Issue

### ISSUE THREAD

**Issue by ThatCuriousGuy** [Traagen/Render-Terrain#1]
I'm hobbyist and just wanted to play around with this thing and your tutorials see what I could learn from it. 

After compiling the project the following always occurs:
http://imgur.com/a/7YtxQ
I have moved the *.png files to the output dir as well. I also tried not loading the terrain which results in a crash because the Scene class depends on those maps without checking if they got loaded. Tried fullscreen and windowed mode. Will try 2d mode and report back. Maybe try to disable terrain loading?

My hardware:
Intel i7 4790k
NVIDIA Geforce 980ti
Latest drivers

**Comment by Traagen** [comment]
Yes. Sorry about that. If it's working correctly, that should be animated. What you're looking at is the shadow map.
I'm afraid this is a pretty good indication that my blog doesn't make a very good tutorial.
The program is supposed to display the height map in 2D, but I switched it to show the shadow map while I was working on shadows and have not switched it back yet. I don't think I ever actually mentioned doing that anywhere.
If you want to switch it back to the height map yourself, open RenderTerrain2dPS.hlsl and you'll see the commented out chunk. Just uncomment that and either delete the bit about shadows or comment it out. 
I'm about to hunt down a bug that I think has to do with the shadows, then I'll switch it back myself.

**Comment by ThatCuriousGuy** [comment]
Thanks seems to working pretty cool. Another issue I ran into was missing files. 
Terrain.cpp line 29-32:

```
    LoadDetailMap(0,` "grassnormalmap.png");
    LoadDetailMap(1,` "dirtnormalmap.png");
    LoadDetailMap(2, "rocknormalmap.png");
    LoadDetailMap(3, "snownormalmap.png");
```

Removing normalmap from the filenames and being sure to move the *.png files included to the compile output dir fix this.

Also another question everything is turning black when approaching the ground is this because the shadowmap bug? What should I look at?

**Comment by Traagen** [comment]
Woops. I didn't realize those files weren't included in the repository. I've added them now. The files like grass.png and rock.png are actually diffuse textures. I haven't added them yet and I'm not entirely sure when/if I will. They would replace the simple colour palette I'm currently using. But you don't want to use them as normals. You'll likely get weird results, which some quick testing makes me think is actually the black you're seeing.
The normal maps are created from those diffuse maps, but look quite different and produce much better results.
If you did want to use those diffuse maps, the code won't support both at once as it currently stands, but you could modify the pixel shader to use the diffuse maps instead of the normal maps. In fact, I have uploaded a new version now that does just that. If you grab the new RenderTerrainTessPS.hlsl and check out the main, you'll see a commented out line calling height_and_slope_based_texture(). If you comment the 2 directly preceding lines and uncomment that one line, then set the terrain to load the diffuse maps as you have previously done, the terrain will be textured with the diffuse maps. It won't have normal mapping, however. 
To have both at once, we'll need to bind more textures. Now that I've actually seen how the diffuse textures look, I'll likely add this at some point, but I've got bugs to fix and want to rewrite most of the program first. 
Plus, on my GPU, a 680, I'm already at the point where I'm barely scraping 30fps. If I add diffuse texturing on top of normal mapping, I'll be well below as that will pretty much double the number of texture samples I need. I'll need to look at ways of optimizing or that won't run very well. That may be less of an issue for a newer card like your own.

The shadow map bug is most obvious if you hit space to pause the time of day cycle at some point and then wander about the terrain looking around. You'll occasionally find points where if you face in a certain direction, shadows that shouldn't be there will glitch into being and out again as you look away. Very weird.
There's also a second bug I haven't really mentioned at all on my blog where just before dawn there is a brief moment, only visible at certain locations, where it appears the light source is still shining through the map. I expect that will be either a problem with the skirt around the edge of the terrain, or with the skirt getting clipped during the shadow mapping phase.

About the whole needing to move the files. I'm not sure why that would be. I just have the png files in the same directory as all of my source files and it loads fine. If I compile as Release instead of Debug, then I believe I do need to copy/move the files to the same directory as the executable. I may have a setting somewhere that allows the Debug mode to access the source directory.

**Comment by Traagen** [comment]
Shadow map bugs should be fixed. I'll leave this issue open for now in case you see anything else related to the original issues.

**Comment by Traagen** [comment]
No further word and I haven't seen any issues myself. Closing issue.
